version: "3.9"

services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: storage-service-mosquitto
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped

  storage-service:
    build: .
    container_name: storage
    depends_on:
      - mosquitto
    environment:
      BROKER: mosquitto
      PORT: 1883
    restart: unless-stopped
